language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

install:
  - composer install

script:
  - phpunit
  - vendor/bin/phpcs -n -p --encoding=utf-8 --standard=PSR2 --extensions=php ./src/ ./tests/
